[WIP] Add BM1370 support
GPTechinno/bm13xx-rs pull request #3
Opened 2024-11-24 15:11 UTC by DanielWarloch

The work is still in progress. The first I wanned get ASICs working(a few shares accepted) and then I planned do a proper clean up.

2024-11-25 09:58 UTC, Georges760 commented
Thx a lot Daniel for your contribution, I will review this carefully asap.

2024-11-25 16:14 UTC, Georges760 requested changes
Lot to discuss, but it is normal for such a complex chip/crate

2024-11-25 16:14 UTC, Georges760 commented on bm1366/Cargo.toml
> +log = ["dep:log"]
should not be necessary, isn't it ?

2024-11-25 16:14 UTC, Georges760 commented on bm1370/Cargo.toml
> +    log = ["dep:log"]
necessary ?

2024-11-25 16:14 UTC, Georges760 commented on bm1370/src/lib.rs
> +pub const BM1370_CORE_CNT: usize = 80;
should be 128 for BM1370, 80 is for BM1368

2024-11-25 16:14 UTC, Georges760 commented on bm1370/src/lib.rs
> +pub const BM1370_SMALL_CORE_CNT: usize = 894;
should be 2040

2024-11-25 16:14 UTC, Georges760 commented on bm1370/src/lib.rs
> +pub const BM1370_DOMAIN_CNT: usize = 1;
should be 4

2024-11-25 16:14 UTC, Georges760 commented on bm1370/src/lib.rs
> +pub const BM1370_PLL_CNT: usize = 4;
are you sure BM1370 has 4 PLL? below you define register only for the 3rd one (PLL2)

2024-11-25 16:14 UTC, Georges760 commented on bm1370/src/lib.rs
> +pub const BM1370_NONCE_CORES_BITS: usize = 7; // Core ID is hardcoded on Nonce[31:25] -> 7 bits
are you sure about that ? (how the asic split a nonce space between its core and small cores)

2024-11-25 16:14 UTC, Georges760 commented on bm1370/src/lib.rs
> +pub const BM1370_PLL_ID_UART: usize = 1; // PLL1 can be used for UART Baudrate
should be 3, in my S21Pro communication trace, BM1370 use PLL3 to set the UART baudrate

2024-11-25 16:14 UTC, Georges760 commented on bm1370/src/lib.rs
> +pub const BM1370_PLL_OUT_UART: usize = 4; // specifically PLL1_OUT4 can be used for UART Baudrate
TODO: see send_baudrate() below

2024-11-25 16:14 UTC, Georges760 commented on bm1370/src/lib.rs
> +    /// let mut baud_seq = bm1370.send_baudrate(6_250_000);
send_baudrate() need to be rewriten, it is not the same as BM1366
example to respect (from S21Pro and S21XP comm trace):
```rust
let mut baud_seq = bm1370.send_baudrate(3_125_000);
assert_eq!(baud_seq.len(), 2);
assert_eq!(baud_seq.pop().unwrap().cmd, [0x55, 0xaa, 0x51, 0x09, 0x00, 0x28, 0x01, 0x30, 0x00, 0x00, 0x1a]); // FastUartConfiguration
// here there are a bunch of UartRelay writing according to the Chain Voltage Domain stackup (let's forget them for now)
assert_eq!(baud_seq.pop().unwrap().cmd, [0x55, 0xaa, 0x51, 0x09, 0x00, 0x68, 0x5a, 0xa5, 0x5a, 0xa5, 0x1c]); // Pll3Paramter
// here there are a bunch of IoDriverStrenghtConfiguration writing according to the Chain Voltage Domain stackup (let's forget them for now)
assert!(bm1370.plls[BM1370_PLL_ID_UART].enabled());
assert_eq!(bm1370.registers.get(&PLL3Parameter::ADDR).unwrap(), &0x5aa5_5aa5);
assert_eq!(bm1370.registers.get(&FastUARTConfigurationV2::ADDR).unwrap(), &0x0130_0000); // is it v2 or not ?
```

2024-11-25 16:14 UTC, Georges760 commented on bm1370/src/lib.rs
> +        // 1 - [55, AA, 51, 09, 00, A8, 00, 07, 00, 00, 03]
where did you get this list of init command ? I guess from ESP-Miner.
I don't use them, prefering the list from Bitmain official FW, so here under I will give you the data I want to use

2024-11-25 16:14 UTC, Georges760 commented on bm1370/src/lib.rs
> +    /// assert_eq!(init_seq.pop().unwrap().cmd, [0x55, 0xaa, 0x41, 0x09, 0x12, 0x2c, 0x00, 0x18, 0x00, 0x03, 0x0c]);
this example need to be rewritten witht he actual cmds list

2024-11-25 16:14 UTC, Georges760 commented on bm1370/src/lib.rs
> +        // 2 - [55, AA, 51, 09, 00, 18, FF, 0F, C1, 00, 00]
This MiscControl and above Reg8 are part of the send_reset_core() and not the send_init(), please remove from here and look at the commend I am doing there

2024-11-25 16:14 UTC, Georges760 commented on bm1370/src/lib.rs
> +    /// let mut reset_seq = bm1370.send_reset_core(Destination::All);
both S21Pro and S21XP show this sequence :
```rust
let mut reset_seq = bm1370.send_reset_core(Destination::All);
assert_eq!(reset_seq.len(), 2);
assert_eq!(reset_seq.pop().unwrap().cmd, [0x55, 0xaa, 0x51, 0x09, 0x00, 0x18, 0xf0, 0x00, 0xc1, 0x00, 0x04]);
assert_eq!(reset_seq.pop().unwrap().cmd, [0x55, 0xaa, 0x51, 0x09, 0x00, 0xa8, 0x00, 0x07, 0x00, 0x00, 0x03]);
```

2024-11-25 16:14 UTC, Georges760 commented on bm1370/src/lib.rs
> +        // 3 - [55, AA, 51, 09, 00, 3C, 80, 00, 8B, 00, 12]
Agreed, this CoreReg11 writing to 0x00 is the first command of the send_inti() sequence (both S21Pro and S21XP)

2024-11-25 16:14 UTC, Georges760 commented on bm1370/src/lib.rs
> +        // 4 - [55, AA, 51, 09, 00, 3C, 80, 00, 8B, 00, 12]
why send them twice, Bitmain offciial FW send it only once, I would remove the second one

2024-11-25 16:14 UTC, Georges760 commented on bm1370/src/lib.rs
> +        // 5 - [55, AA, 51, 09, 00, 3C, 80, 00, 80, 18, 1F]
S21Pro FW send [55, AA, 51, 09, 00, 3C, 80, 00, 80, 0C, 11]
S21XP FW send [55, AA, 51, 09, 00, 3C, 80, 00, 80, 10, 12]
why ESP-Miner is sending 0x18 ? we need to understand and choose or impl both with parameter

2024-11-25 16:14 UTC, Georges760 commented on bm1370/src/lib.rs
> +        // 7 - [55, AA, 51, 09, 00, 54, 00, 00, 00, 03, 1D]
S21Pro FW doesn't have this AnalogMuxControl step
S21XP FW has it with same value
we need to understand why and choose if we keep it or not.
Is 0x0000_0003 the default value at reset ?

2024-11-25 16:14 UTC, Georges760 commented on bm1370/src/lib.rs
> +        // last chip of each voltage domain should have IoDriverStrenghtConfiguration set to 0x0211_f111
both S21Proa nd S21XP have this same logic for "last chip of each voltage domain IoDriverStrenghtConfiguration" but value are differents:
- S21Pro -> 0x0001_F111
- S21XP -> 0x0001_3111
It should be related to HW on the Hashboard and how the signals cross the Voltage Domains. We need to compare those 2 HB and understand how to use this register properly

2024-11-25 16:14 UTC, Georges760 commented on bm1370/src/lib.rs
> +        }
here S21Pro and S21XP both have an intermediary step to write PLL3_Parameter register (see comment below) which should be part of send_baudrate(). This enterlacing will make our driver more complex. Need to find a clean way to handle this.

2024-11-25 16:14 UTC, Georges760 commented on bm1370/src/lib.rs
> +        // first and last chip of each voltage domain should have UARTRelay with GAP_CNT=domain_asic_num*(chain_domain_num-domain_i)+14 and RO_REL_EN=CO_REL_EN=1
not sure about the formula, but here are the value I see:
S21Pro: (which has 5 chips per domain and 13 domains total, chip_interval=2 this means chips only use the even chip_addr values)
- chip_addr 120 and 128 -> 0x0013_0003
- chip_addr 110 and 118 -> 0x0018_0003
- chip_addr 100 and 108 -> 0x001D_0003
- chip_addr 90 and 98 -> 0x0022_0003
- chip_addr 80 and 88 -> 0x0027_0003
- chip_addr 70 and 78 -> 0x002C_0003
- chip_addr 60 and 68 -> 0x0031_0003
- chip_addr 50 and 58 -> 0x0036_0003
- chip_addr 40 and 48 -> 0x003B_0003
- chip_addr 30 and 38 -> 0x0040_0003
- chip_addr 20 and 28 -> 0x0045_0003
- chip_addr 10 and 18 -> 0x004A_0003
- chip_addr 0 and 8 -> 0x004F_0003
S21XP: (which has 7 chips per domain and 13 domains total, chip_interval=2 this means chips only use the even chip_addr values)
- chip_addr 168 and 180 -> 0x0015_0003
- chip_addr 154 and 166 -> 0x001C_0003
- chip_addr 140 and 152 -> 0x0023_0003
- chip_addr 126 and 138 -> 0x002A_0003
- chip_addr 112 and 124 -> 0x0031_0003
- chip_addr 98 and 110 -> 0x0038_0003
- chip_addr 84 and 96 -> 0x003F_0003
- chip_addr 70 and 82 -> 0x0046_0003
- chip_addr 56 and 68 -> 0x004D_0003
- chip_addr 42 and 54 -> 0x0054_0003
- chip_addr 28 and 40 -> 0x005B_0003
- chip_addr 14 and 26 -> 0x0062_0003
- chip_addr 0 and 12 -> 0x0069_0003

2024-11-25 16:14 UTC, Georges760 commented on bm1370/src/lib.rs
> +        // In ESP miner here is a for loop and they address cheep one by one
the below sequence is not part of send_init(), but explain send_reset_core() with a specific chip destination
see second example below

2024-11-25 16:14 UTC, Georges760 commented on bm1370/src/lib.rs
> +    /// let mut reset_seq = bm1370.send_reset_core(Destination::Chip(0));
here are the values from S21Pro FW:
```rust
let mut reset_seq = bm1370.send_reset_core(Destination::Chip(0));
assert_eq!(reset_seq.len(), 5);
assert_eq!(reset_seq.pop().unwrap().cmd, [0x55, 0xaa, 0x41, 0x09, 0x00, 0x3c, 0x80, 0x00, 0x82, 0xaa, 0x05]);
assert_eq!(reset_seq.pop().unwrap().cmd, [0x55, 0xaa, 0x41, 0x09, 0x00, 0x3c, 0x80, 0x00, 0x80, 0x0C, 0x19]);
assert_eq!(reset_seq.pop().unwrap().cmd, [0x55, 0xaa, 0x41, 0x09, 0x00, 0x3c, 0x80, 0x00, 0x8B, 0x00, 0x1A]);
assert_eq!(reset_seq.pop().unwrap().cmd, [0x55, 0xaa, 0x41, 0x09, 0x00, 0x18, 0xf0, 0x00, 0xc1, 0x00, 0x0c]);
assert_eq!(reset_seq.pop().unwrap().cmd, [0x55, 0xaa, 0x41, 0x09, 0x00, 0xa8, 0x00, 0x07, 0x01, 0xf0, 0x15]);
```
S21XP is same except ClockDelayCtrl = 0x10 (instead of 0x0C)... why ?

2024-11-25 16:14 UTC, Georges760 commented on bm1370/src/lib.rs
> +
after the loop of individual send_reset_core() and before the send_hash_freq(), both S21Pro and S21XP sned this sequence of 4 commands:
- [0x55, 0xaa, 0x51, 0x09, 0x00, 0xB9, 0x00, 0x00, 0x44, 0x80, 0x0D] // RegB9 ?
- delay 20ms
- [0x55, 0xaa, 0x51, 0x09, 0x00, 0x54, 0x00, 0x00, 0x00, 0x02 0x18] // AnalogMuxControl
- delay 100ms
- [0x55, 0xaa, 0x51, 0x09, 0x00, 0xB9, 0x00, 0x00, 0x44, 0x80, 0x0D] // RegB9 ?
- delay 20ms
- [0x55, 0xaa, 0x51, 0x09, 0x00, 0x3C, 0x80, 0x00, 0x8D, 0xEE, 0x1B] // CoreReg13 = 0xEE
- delay 100ms ?

2024-11-25 16:14 UTC, Georges760 commented on bm1370/src/lib.rs
> +        if self.plls[BM1370_PLL_ID_HASH].out_div(BM1370_PLL_OUT_HASH) != 0 {
no PLL0Divider writing at all for BM1370 FW

2024-11-25 16:14 UTC, Georges760 commented on bm1370/src/lib.rs
> +            if freq > HertzU64::MHz(380) {
this delay change is different on BM1370:
on S21XP FW: 
- 1 delay of 26.4s between 350MHz and 356.25MHz
- back to 400ms until 418.75MHz 
- then 1 delay of 8.4s before the 425MHz
- back to 400ms until the end at 447.9MHz
on S21Pro FW:
- 1 delay of 2.7s between 556.25MHz and 562.5MHz
- 1 delay of 400ms until 568.75MHz
- 1 delay of 2.7s until 575MHz
- 1 delay of 400ms until 587.5MHz
- 1 delay of 2.7s until 593.75MHz
- 1 delay of 400ms until 600MHz
- 1 delay of 2.7s until a second 600MHz
why ?

2024-11-25 16:14 UTC, Georges760 commented on bm1370/src/lib.rs
> +        let hcn = 0x0000_151c;
S21Pro: hcn = 0x0000_1EB5
S21XP: hcn = 0x0000_1A44

@adam_west has a lot to explain for them

2024-11-25 16:14 UTC, Georges760 commented on bm1370/src/lib.rs
> +
S21Pro only has an intermediary step between send_hash_freq() and send_version_rolling():
writing each individual chip register ChipNonceOffset with values
- starting at 0x8000_0000 for chip_addr 0
- 0x8000_03F1 for chip_addr 2
- 0x8000_07E1 for chip_addr 4
- 0x8000_0BD1 for chip_addr 6
- ...
- 0x8000_FC10 for chip_addr 128

2024-11-25 16:14 UTC, Georges760 commented on bm13xx-asic/Cargo.toml
> +log = ["dep:log"]
necessary ?

2024-11-25 16:14 UTC, Georges760 commented on bm13xx-chain/src/lib.rs
> +
great refactor, have to check that closely

2024-11-25 16:14 UTC, Georges760 commented on bm13xx-protocol/Cargo.toml
> +log = ["dep:log"]
necessary?

2024-11-25 16:14 UTC, Georges760 commented on bm13xx-chain/src/lib.rs
> +    pub async fn send_job(&mut self, job: &[u8]) -> Result<u8, P::Error> {
this this API was missing, but could we use a more specific Job type ? bm13xx_protocol expose job_midstate() for chip without hardware version rolling enabled and job_header() for chip with hardware version rolling enabled. So could we add a version_rolling_enabled bool in the Chain struct, which turn true only if set_version_rolling() succeed, and leverage this knowledge to know which kind of bm13xx_protocol::job_xxx() call to construct the set_job() frame then send it like you do.

2024-11-25 16:14 UTC, Georges760 commented on bm13xx-chain/src/lib.rs
> +    pub async fn read_job(&mut self, job: &mut [u8]) -> Result<u8, P::Error> {
this read_job should be more generic to read any frame from the chip chain.
it should do the framing according to the 0xAA 0x55 start of frame marker, so should accumulate in a buffer using a self.port.read (not read_exact) to construct the framing
it should use bm13xx_protocol::Response::parse() or Response::parse_version() (according to the hardware_version_rolling_enabled state) and return a Response properly parsed

2024-11-25 16:14 UTC, Georges760 commented on bm1370/src/lib.rs
> +        bm1370.registers.insert(RegD8::ADDR, 0x0000_0000).unwrap();
how did you get these new default value ? did you use the bm13xx_protocol reg_probe example ?

2024-11-25 16:14 UTC, Georges760 commented on bm1370/src/lib.rs
> +        bm1370.core_registers.insert(CoreReg11::ID, 0x00).unwrap(); // TODO: Check initial value
you can use bm13xx_protocol core_reg_probe example to know all these default values

2024-11-25 16:14 UTC, Georges760 commented on bm1370/src/lib.rs
> +        bm1370
where is PLL3Parameter ?

2024-11-25 16:14 UTC, Georges760 commented on bm1370/src/lib.rs
> +        bm1370
PLL2Divider and PLL3Divider ?

2024-11-26 17:08 UTC, DanielWarloch commented on bm1370/src/lib.rs
> +        bm1370.registers.insert(RegD8::ADDR, 0x0000_0000).unwrap();
yes, here is the output that I got:
```
Read register 0x00
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 0, reg_value: 13700000 }
Read register 0x04
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 4, reg_value: 0 }
Read register 0x08
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 8, reg_value: c0540165 }
Read register 0x0c
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: c, reg_value: 0 }
Read register 0x10
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 10, reg_value: 0 }
Read register 0x14
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 14, reg_value: 0 }
Read register 0x18
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 18, reg_value: c100 }
Read register 0x1c
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 1c, reg_value: 0 }
Read register 0x20
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 20, reg_value: 7 }
Read register 0x24
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 24, reg_value: 100000 }
Read register 0x28
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 28, reg_value: 1301a00 }
Read register 0x2c
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 2c, reg_value: f0000 }
Read register 0x30
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 30, reg_value: 80 }
Read register 0x34
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 34, reg_value: 0 }
Read register 0x38
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 38, reg_value: 0 }
Read register 0x3c
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 3c, reg_value: 0 }
Read register 0x40
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 8020100 }
Read register 0x44
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 44, reg_value: 0 }
Read register 0x48
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 48, reg_value: 0 }
Read register 0x4c
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 4c, reg_value: 0 }
Read register 0x50
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 50, reg_value: 0 }
Read register 0x54
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 54, reg_value: 0 }
Read register 0x58
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 58, reg_value: 12111 }
Read register 0x5c
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 5c, reg_value: ffff }
Read register 0x60
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 60, reg_value: 20500174 }
Read register 0x64
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 64, reg_value: 20500174 }
Read register 0x68
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 68, reg_value: 0 }
Read register 0x6c
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 6c, reg_value: 10200 }
Read register 0x70
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 70, reg_value: 0 }
Read register 0x74
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 74, reg_value: 0 }
Read register 0x78
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 78, reg_value: 0 }
Read register 0x7c
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 7c, reg_value: 0 }
Read register 0x80
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 80, reg_value: 0 }
Read register 0x84
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 84, reg_value: 0 }
Read register 0x88
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 88, reg_value: 0 }
Read register 0x8c
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 8c, reg_value: 0 }
Read register 0x90
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 90, reg_value: 0 }
Read register 0x94
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 94, reg_value: 0 }
Read register 0x98
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 98, reg_value: 0 }
Read register 0x9c
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 9c, reg_value: f70073 }
Read register 0xa0
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: a0, reg_value: 0 }
Read register 0xa4
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: a4, reg_value: ffff }
Read register 0xa8
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: a8, reg_value: 70000 }
Read register 0xac
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: ac, reg_value: 0 }
Read register 0xb0
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: b0, reg_value: 0 }
Read register 0xb4
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: b4, reg_value: 0 }
Read register 0xb8
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: b8, reg_value: 20000000 }
Read register 0xbc
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: bc, reg_value: 3313 }
Read register 0xc0
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: c0, reg_value: 2000 }
Read register 0xc4
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: c4, reg_value: b850 }
Read register 0xc8
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: c8, reg_value: 0 }
Read register 0xcc
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: cc, reg_value: 0 }
Read register 0xd0
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: d0, reg_value: 0 }
Read register 0xd4
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: d4, reg_value: 0 }
Read register 0xd8
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: d8, reg_value: 0 }
Read register 0xdc
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: dc, reg_value: 0 }
Read register 0xe0
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: e0, reg_value: 0 }
Read register 0xe4
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: e4, reg_value: 0 }
Read register 0xe8
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: e8, reg_value: 0 }
Read register 0xec
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: ec, reg_value: 0 }
Read register 0xf0
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: f0, reg_value: 0 }
Read register 0xf4
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: f4, reg_value: 0 }
Read register 0xf8
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: f8, reg_value: 0 }
```

2024-11-26 17:31 UTC, DanielWarloch commented on bm1370/src/lib.rs
> +        bm1370.core_registers.insert(CoreReg11::ID, 0x00).unwrap(); // TODO: Check initial value
I tried and do not really understand the output. Why we are getting so many values for single register.
```
Soft Open Core
>> [55, aa, 51, 9, 0, a8, 0, 7, 1, f, 9]
>> [55, aa, 51, 9, 0, 18, ff, 0, c1, 0, 1c]
>> [55, aa, 51, 9, 0, a8, 0, 7, 0, 0, 3]
>> [55, aa, 51, 9, 0, 18, ff, f, c1, 0, 0]
>> [55, aa, 51, 9, 0, 3c, 80, 0, 82, aa, d]
Read all Core Registers
>> [55, aa, 41, 9, 0, 3c, 80, 0, 0, ff, 18]
>> [55, aa, 42, 5, 0, 40, 9]
<< [aa, 55, 0, 0, 0, 52, 0, 40, 10]
.insert(0, 0x52).unwrap()
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 10052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 20052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 30052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 40052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 50052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 60052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 70052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 80052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 90052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: a0052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: b0052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: c0052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: c0052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: d0052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: e0052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: f0052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 100052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 110052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 120052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 130052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 140052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 150052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 160052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 170052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 180052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 190052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 1a0052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 1b0052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 1c0052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 1d0052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 1e0052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 1f0052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 200052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 210052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 220052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 230052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 240052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 250052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 260052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 270052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 280052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 290052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 2a0052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 2b0052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 2c0052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 2d0052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 2e0052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 2f0052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 300052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 310052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 320052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 330052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 340052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 350052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 360052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 370052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 380052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 390052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 3a0052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 3b0052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 3c0052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 3d0052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 3e0052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 3f0052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 400052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 410052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 420052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 430052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 440052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 450052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 460052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 470052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 480052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 490052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 4a0052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 4b0052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 4c0052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 4d0052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 4e0052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 4f0052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 500052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 510052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 520052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 530052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 540052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 550052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 560052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 570052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 580052 }
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 590052 }
        ASIC_0: RegisterResponse { chip_addr: 0, re [...]

2024-11-26 17:56 UTC, DanielWarloch commented on bm1370/src/lib.rs
> +pub const BM1370_CORE_CNT: usize = 80;
fixed

2024-11-26 17:56 UTC, DanielWarloch commented on bm1370/src/lib.rs
> +pub const BM1370_SMALL_CORE_CNT: usize = 894;
fixed

2024-11-26 17:57 UTC, DanielWarloch commented on bm1370/src/lib.rs
> +pub const BM1370_DOMAIN_CNT: usize = 1;
fixed

2024-11-26 18:02 UTC, DanielWarloch commented on bm1370/src/lib.rs
> +pub const BM1370_PLL_CNT: usize = 4;
as you mentioned below PLL3 is used for UART then 4 is probably correct

I added the init values for PLL3 now

2024-11-26 18:09 UTC, DanielWarloch commented on bm1370/src/lib.rs
> +pub const BM1370_NONCE_CORES_BITS: usize = 7; // Core ID is hardcoded on Nonce[31:25] -> 7 bits
I am totally not sure. Removed this comment and marked it as `TODO: Check if is correct`

2024-11-26 18:09 UTC, DanielWarloch commented on bm1370/src/lib.rs
> +pub const BM1370_PLL_ID_UART: usize = 1; // PLL1 can be used for UART Baudrate
fixed

2024-11-26 19:56 UTC, Georges760 commented on bm1370/src/lib.rs
> +pub const BM1370_NONCE_CORES_BITS: usize = 7; // Core ID is hardcoded on Nonce[31:25] -> 7 bits
i will look into bmminer/Ghidra for it

2024-12-04 10:58 UTC, Georges760 commented on bm1370/src/lib.rs
> +        let hcn = 0x0000_151c;
he says (rightfully I think) that HCN is also a function of the hashing frequency, which make lot of sense

2024-12-07 19:48 UTC, DanielWarloch commented on bm1370/src/lib.rs
> +        bm1370
fixed

2024-12-07 19:48 UTC, DanielWarloch commented on bm1370/src/lib.rs
> +        bm1370
fixed

2024-12-07 19:48 UTC, DanielWarloch commented on bm1370/src/lib.rs
> +        // 1 - [55, AA, 51, 09, 00, A8, 00, 07, 00, 00, 03]
yes ESP-Miner. Sure will add commands from original firmware

2024-12-07 19:48 UTC, DanielWarloch commented on bm13xx-chain/src/lib.rs
> +
This still need to be fixed in better way but at least allows to enumerate a few asics

2024-12-07 19:48 UTC, DanielWarloch commented on bm1366/Cargo.toml
> +log = ["dep:log"]
I will check that but I think if you mark the dependency as optional then you need a feature to compile it.

2024-12-07 19:48 UTC, DanielWarloch commented on bm1370/Cargo.toml
> +    log = ["dep:log"]
I will check that but I think if you mark the dependency as optional then you need a feature to compile it.

2024-12-11 16:35 UTC, Georges760 requested changes

2024-12-11 16:35 UTC, Georges760 commented on bm1370/src/lib.rs
> +            .insert(HashRate::ADDR, 0x0001_2a89)
you said to have read:
```
Read register 0x04
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 4, reg_value: 0 }
```
so it should be 0x0000_0000 here

2024-12-11 16:35 UTC, Georges760 commented on bm1370/src/lib.rs
> +            // .insert(OrderedClockEnable::ADDR, 0x0000_0003) // NOTE: Changed from 1360
you can remove this line (comment) not usefull anymore

2024-12-11 16:35 UTC, Georges760 commented on bm1370/src/lib.rs
> +        // bm1370.registers.insert(Reg30::ADDR, 0x0000_0070).unwrap(); // NOTE: changed from 1360
you can remove this line (comment) not usefull anymore

2024-12-11 16:35 UTC, Georges760 commented on bm1370/src/lib.rs
> +            .insert(CoreRegisterValue::ADDR, 0x007f_0000)
you said to have read:
```
Read register 0x40
        ASIC_0: RegisterResponse { chip_addr: 0, reg_addr: 40, reg_value: 8020100 }
```
so it should be 0x0802_0100 here

(it is not very important because CoreRegisterValue is meaningless without a write to CoreRegisterControl first, but even knowing that we should put the default reste value here)

2024-12-11 16:35 UTC, Georges760 commented on bm1370/src/lib.rs
> +            // .insert(CoreRegisterValue::ADDR, 0x1eaf_5fbe) // NOTE: changed from 1360
you can remove this line (comment) not usefull anymore

2024-12-11 16:35 UTC, Georges760 commented on bm1370/src/lib.rs
> +            .insert(PLL2Parameter::ADDR, 0x2050_0174) // NOTE: Added by dwarloch
you can remove the comment, git log will show what was your contribution ;)

2024-12-11 16:35 UTC, Georges760 commented on bm1370/src/lib.rs
> +        bm1370
HashCountingNumber already declared above, remove this insert, please

2024-12-11 16:35 UTC, Georges760 commented on bm1370/src/lib.rs
> +        bm1370.core_registers.insert(CoreReg11::ID, 0x00).unwrap(); // TODO: Check initial value
only the `.insert(1, 0x00).unwrap()` are interesting, the other are there to debug

`.insert(0, 0x52).unwrap()` => core register ID=0 (ClockDelayCtrlV2), default value = 0x52
`.insert(1, 0x00).unwrap()` => core register ID=1, default value = 0x00
etc...

2024-12-11 16:35 UTC, Georges760 commented on bm1370/src/lib.rs
> +            .insert(ClockDelayCtrlV2::ID, 0x98)
this should be 0x52 according to your log below

2024-12-11 16:35 UTC, Georges760 commented on bm1370/src/lib.rs
> +        // bm1370.core_registers.insert(1, 0x00).unwrap(); // not used anywhere in official FW
this is 0x00 as shown in your log, but I choosed to not declare unknown CoreRegister if their default value is 0, that's why it is commented

2024-12-11 16:35 UTC, Georges760 commented on bm1370/src/lib.rs
> +        bm1370.core_registers.insert(CoreReg11::ID, 0x00).unwrap(); // TODO: Check initial value
can you send me the full log ?

2024-12-11 16:35 UTC, Georges760 commented on bm1370/src/lib.rs
> +
i will find a wait to add this after this PR merged (and some Ghidra effort) ;)

2024-12-11 16:35 UTC, Georges760 commented on bm1370/src/lib.rs
> +
i will take care of this extra step after this PR merged

2024-12-11 16:35 UTC, Georges760 commented on bm13xx-chain/src/lib.rs
> +    pub async fn read_job(&mut self, job: &mut [u8]) -> Result<u8, P::Error> {
I will take care of it after this PR merged

2024-12-11 16:37 UTC, Georges760 commented
@DanielWarloch I close all complex comments, only the easy to fix ones, for you to finish this (big) PR. Then after merging it, I will work on master to add the missing parts.

2024-12-21 17:44 UTC, DanielWarloch commented on bm1370/src/lib.rs
> +        // bm1370.core_registers.insert(1, 0x00).unwrap(); // not used anywhere in official FW
I can't paste the log in comment below so I am pasting the full log here.

[read_regs.log](https://github.com/user-attachments/files/18219436/read_regs.log)

2025-01-02 09:07 UTC, Georges760 approved these changes
Good to merge, I will finish it later in main

2025-01-02 09:10 UTC, merged